{"level":"error"}
{"level":"error"}
{"level":"error"}
{"level":"error","message":"Unexpected token < in JSON at position 0 Unexpected token < in JSON at position 0","stack":"SyntaxError: Unexpected token < in JSON at position 0\n    at JSON.parse (<anonymous>)\n    at loadAllMeasurements (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\modules\\measurement.js:36:29)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
{"level":"error","message":"Failed in fetching data from Open AQ platform API. Failed in fetching data from Open AQ platform API.","stack":"Error: Failed in fetching data from Open AQ platform API.\n    at loadAllMeasurements (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\modules\\measurement.js:42:19)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
{"error":{},"level":"error","message":"uncaughtException: datasourceUrl is not defined\nReferenceError: datasourceUrl is not defined\n    at mongoose.connect.then (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\startup\\db.js:13:33)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","stack":"ReferenceError: datasourceUrl is not defined\n    at mongoose.connect.then (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\startup\\db.js:13:33)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","exception":true,"date":"Sat Dec 05 2020 22:42:30 GMT+0100 (Central European Standard Time)","process":{"pid":17568,"uid":null,"gid":null,"cwd":"C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend","execPath":"C:\\Program Files\\nodejs\\node.exe","version":"v10.16.3","argv":["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\index.js"],"memoryUsage":{"rss":71741440,"heapTotal":60551168,"heapUsed":24425792,"external":18810091}},"os":{"loadavg":[0,0,0],"uptime":184042},"trace":[{"column":33,"file":"C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\startup\\db.js","function":"mongoose.connect.then","line":13,"method":"then","native":false},{"column":7,"file":"internal/process/next_tick.js","function":"process._tickCallback","line":68,"method":"_tickCallback","native":false}]}
{"error":{},"level":"error","message":"uncaughtException: datasourceUrl is not defined\nReferenceError: datasourceUrl is not defined\n    at mongoose.connect.then (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\startup\\db.js:13:33)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","stack":"ReferenceError: datasourceUrl is not defined\n    at mongoose.connect.then (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\startup\\db.js:13:33)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","exception":true,"date":"Sat Dec 05 2020 22:42:30 GMT+0100 (Central European Standard Time)","process":{"pid":17568,"uid":null,"gid":null,"cwd":"C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend","execPath":"C:\\Program Files\\nodejs\\node.exe","version":"v10.16.3","argv":["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\index.js"],"memoryUsage":{"rss":71741440,"heapTotal":60551168,"heapUsed":24425792,"external":18810091}},"os":{"loadavg":[0,0,0],"uptime":184042},"trace":[{"column":33,"file":"C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\startup\\db.js","function":"mongoose.connect.then","line":13,"method":"then","native":false},{"column":7,"file":"internal/process/next_tick.js","function":"process._tickCallback","line":68,"method":"_tickCallback","native":false}]}
{"error":{},"level":"error","message":"uncaughtException: config is not defined\nReferenceError: config is not defined\n    at module.exports (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\startup\\models.js:4:27)\n    at Object.<anonymous> (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\index.js:6:28)\n    at Module._compile (internal/modules/cjs/loader.js:778:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)","stack":"ReferenceError: config is not defined\n    at module.exports (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\startup\\models.js:4:27)\n    at Object.<anonymous> (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\index.js:6:28)\n    at Module._compile (internal/modules/cjs/loader.js:778:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)","exception":true,"date":"Sat Dec 05 2020 22:51:27 GMT+0100 (Central European Standard Time)","process":{"pid":15640,"uid":null,"gid":null,"cwd":"C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend","execPath":"C:\\Program Files\\nodejs\\node.exe","version":"v10.16.3","argv":["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\index.js"],"memoryUsage":{"rss":68349952,"heapTotal":57405440,"heapUsed":33465720,"external":19467168}},"os":{"loadavg":[0,0,0],"uptime":184579},"trace":[{"column":27,"file":"C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\startup\\models.js","function":"module.exports","line":4,"method":"exports","native":false},{"column":28,"file":"C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\index.js","function":null,"line":6,"method":null,"native":false},{"column":30,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":778,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":789,"method":".js","native":false},{"column":32,"file":"internal/modules/cjs/loader.js","function":"Module.load","line":653,"method":"load","native":false},{"column":12,"file":"internal/modules/cjs/loader.js","function":"tryModuleLoad","line":593,"method":null,"native":false},{"column":3,"file":"internal/modules/cjs/loader.js","function":"Module._load","line":585,"method":"_load","native":false},{"column":12,"file":"internal/modules/cjs/loader.js","function":"Module.runMain","line":831,"method":"runMain","native":false},{"column":19,"file":"internal/bootstrap/node.js","function":"startup","line":283,"method":null,"native":false},{"column":3,"file":"internal/bootstrap/node.js","function":"bootstrapNodeJSCore","line":622,"method":null,"native":false}]}
{"error":{},"level":"error","message":"uncaughtException: config is not defined\nReferenceError: config is not defined\n    at module.exports (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\startup\\models.js:4:27)\n    at Object.<anonymous> (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\index.js:6:28)\n    at Module._compile (internal/modules/cjs/loader.js:778:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)","stack":"ReferenceError: config is not defined\n    at module.exports (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\startup\\models.js:4:27)\n    at Object.<anonymous> (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\index.js:6:28)\n    at Module._compile (internal/modules/cjs/loader.js:778:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)","exception":true,"date":"Sat Dec 05 2020 22:51:27 GMT+0100 (Central European Standard Time)","process":{"pid":15640,"uid":null,"gid":null,"cwd":"C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend","execPath":"C:\\Program Files\\nodejs\\node.exe","version":"v10.16.3","argv":["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\index.js"],"memoryUsage":{"rss":68349952,"heapTotal":57405440,"heapUsed":33465720,"external":19467168}},"os":{"loadavg":[0,0,0],"uptime":184579},"trace":[{"column":27,"file":"C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\startup\\models.js","function":"module.exports","line":4,"method":"exports","native":false},{"column":28,"file":"C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\index.js","function":null,"line":6,"method":null,"native":false},{"column":30,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":778,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":789,"method":".js","native":false},{"column":32,"file":"internal/modules/cjs/loader.js","function":"Module.load","line":653,"method":"load","native":false},{"column":12,"file":"internal/modules/cjs/loader.js","function":"tryModuleLoad","line":593,"method":null,"native":false},{"column":3,"file":"internal/modules/cjs/loader.js","function":"Module._load","line":585,"method":"_load","native":false},{"column":12,"file":"internal/modules/cjs/loader.js","function":"Module.runMain","line":831,"method":"runMain","native":false},{"column":19,"file":"internal/bootstrap/node.js","function":"startup","line":283,"method":null,"native":false},{"column":3,"file":"internal/bootstrap/node.js","function":"bootstrapNodeJSCore","line":622,"method":null,"native":false}]}
{"errors":{"_id":{}},"_message":"Measurement validation failed","level":"error","message":"Measurement validation failed: _id: Right-hand side of 'instanceof' is not callable Measurement validation failed: _id: Right-hand side of 'instanceof' is not callable","stack":"ValidationError: Measurement validation failed: _id: Right-hand side of 'instanceof' is not callable\n    at model.Object.<anonymous>.Document.invalidate (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\mongoose\\lib\\document.js:2688:32)\n    at $__applyDefaults (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\mongoose\\lib\\document.js:432:17)\n    at model.Document (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\mongoose\\lib\\document.js:139:7)\n    at model.Model (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\mongoose\\lib\\model.js:105:12)\n    at new model (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\mongoose\\lib\\model.js:4689:15)\n    at toExecute.push.callback (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\mongoose\\lib\\model.js:3055:22)\n    at toExecute.forEach (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\mongoose\\lib\\model.js:3091:7)\n    at Array.forEach (<anonymous>)\n    at db.base._promiseOrCallback.cb (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\mongoose\\lib\\model.js:3090:15)\n    at Promise (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:5)\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:30:10)\n    at Mongoose.Object.<anonymous>.Mongoose._promiseOrCallback (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\mongoose\\lib\\index.js:1135:10)\n    at Function.create (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\mongoose\\lib\\model.js:3025:23)\n    at loadAllMeasurements (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\models\\measurement.js:39:47)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
{"level":"error","message":"Failed in fetching data from Open AQ platform API. Failed in fetching data from Open AQ platform API.","stack":"Error: Failed in fetching data from Open AQ platform API.\n    at loadAllMeasurements (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\models\\measurement.js:42:19)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
{"level":"error","message":"Failed in fetching data from Open AQ platform API. Please try later again. Failed in fetching data from Open AQ platform API. Please try later again.","stack":"Error: Failed in fetching data from Open AQ platform API. Please try later again.\n    at loadAllMeasurements (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\models\\measurement.js:42:19)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
{"level":"error","message":"Failed in fetching data from Open AQ platform API. Please try later again. Failed in fetching data from Open AQ platform API. Please try later again.","stack":"Error: Failed in fetching data from Open AQ platform API. Please try later again.\n    at loadAllMeasurements (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\models\\measurement.js:42:19)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
{"level":"error","message":"Failed in fetching data from Open AQ platform API. Please try later again. Failed in fetching data from Open AQ platform API. Please try later again.","stack":"Error: Failed in fetching data from Open AQ platform API. Please try later again.\n    at loadAllMeasurements (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\models\\measurement.js:42:19)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
{"level":"error","message":"something wrong something wrong","stack":"Error: something wrong\n    at router.get (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\routes\\home.js:6:11)\n    at Layer.handle [as handle_request] (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at newFn (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\express\\lib\\router\\index.js:275:10)"}
{"level":"error","message":"something wrong something wrong","stack":"Error: something wrong\n    at router.get (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\routes\\home.js:5:11)\n    at Layer.handle [as handle_request] (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at newFn (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\Users\\zhang.zhan\\Documents\\GitHub\\Code.Now\\backend\\node_modules\\express\\lib\\router\\index.js:275:10)"}
